def create_level():
    return [
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                          P",
        "P                                          P",
        "P                                          P",
        "P       S            PPPPPPPPPPP           P",
        "P                                          P",
        "P                                          P",
        "P                                          P",
        "P    PPPPPPPPP      P PPP                  P",
        "P            P      P S P                  P",
        "P            P      P   P  PPPPPPP         P",
        "PPPP         P   PPPPPPPPPPP               P",
        "P            P   P     P                   P",
        "P         PPPPPPPP PPPPS                   P",
        "P                P   P                     P",
        "P                P PPPPPPPPPP              P",
        "P                P          P              P",
        "P   PPPPPPPPPPPPPPPPPPPPPP  P              P",
        "P                P E        P              P",
        "P                PPPPPPPPPPPP              P",
        "P                                          P",
        "PPPPPPPP                                   P",
        "P                                          P",
        "P                                          P",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        ]