def create_level():
    return [
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                          P",
        "P                                          P",
        "P                                          P",
        "P                    PPPPPPPPPPP           P",
        "P                                          P",
        "P                                          P",
        "P                                          P",
        "P    PPPPPPPPP                             P",
        "P            P                             P",
        "P            P             PPPPPPP         P",
        "PPPP         P   PPPPPPP                   P",
        "P            P   P                         P",
        "P         PPPPPPPP                         P",
        "P                P                         P",
        "P                P    PPPPPPP              P",
        "P                P          P              P",
        "P   PPPPPPPPPPPPPP          P              P",
        "P                P E        P              P",
        "P                PPPPPPPPPPPP              P",
        "P                                          P",
        "PPPPPPPP                                   P",
        "P                                          P",
        "P                                          P",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        ]