from map import Map
from astar import Search

def main():
    print("*** DEBUT TEST10 *************************************************")
    map = Map('test10.map')
    map.print_as_grid()
    a = Search(map.grid)
    a.process()
    if(a.path_found):
        cells = a.get_path()
        print()
        print(cells)
        print()
        a.display_path_as_grid()
    print("*** FIN TEST10 ***************************************************")
    print()
    print()
    print()
    print("*** DEBUT TEST11 *************************************************")
    map = Map('test11.map')
    map.print_as_grid()

    a = Search(map.grid)
    a.process()
    if(a.path_found):
        cells = a.get_path()
        print()
        print(cells)
        print()
        a.display_path_as_grid()
    print("*** FIN TEST11 ***************************************************")
    print()
    print()
    print()
    print("*** DEBUT TEST12 *************************************************")
    map = Map('test12.map')
    map.print_as_grid()

    a = Search(map.grid)
    a.process()
    if(a.path_found):
        cells = a.get_path()
        print()
        print(cells)
        print()
        a.display_path_as_grid()
    print("*** FIN TEST12 ***************************************************")
    print()
    print()
    print()
    print("*** DEBUT TEST13 *************************************************")
    map = Map('test13.map')
    map.print_as_grid()

    a = Search(map.grid)
    a.process()
    if(a.path_found):
        cells = a.get_path()
        print()
        print(cells)
        print()
        a.display_path_as_grid()
    print("*** FIN TEST13 ***************************************************")
    print()
    print()
    print()
    print("*** DEBUT TEST14 *************************************************")
    map = Map('test14.map')
    map.print_as_grid()

    a = Search(map.grid)
    a.process()
    if(a.path_found):
        cells = a.get_path()
        print()
        print(cells)
        print()
        a.display_path_as_grid()
    print("*** FIN TEST14 ***************************************************")
    print()
    print()
    print()
    print("*** DEBUT TEST15 *************************************************")
    map = Map('test15.map')
    map.print_as_grid()

    a = Search(map.grid)
    a.process()
    if(a.path_found):
        cells = a.get_path()
        print()
        print(cells)
        print()
        a.display_path_as_grid()
    print("*** FIN TEST15 ***************************************************")
    print()
    print()
    print()

if __name__ == "__main__":
    main()

